Ethers v6 new
0xsequence/sequence.js pull request #533
Opened 2024-06-05 19:25 UTC by corbanbrook

2024-07-11 21:46 UTC, attente requested changes

2024-07-11 21:46 UTC, attente commented on packages/wallet/tests/wallet.spec.ts
> +          expect(nonce === 0n).to.be.true
Guess we can rewrite these to:

```
expect(space).to.equal(6492n)
expect(nonce).to.equal(0n)
```

2024-07-11 21:46 UTC, attente commented on packages/utils/src/bigint.ts
> +}
Probably something like this is simpler:

```
const result = value.toString(16)

return `${result.length % 2 === 0 ? '0x' : '0x0'}${result}`
```

2024-07-11 21:46 UTC, attente commented on packages/utils/src/bigint.ts
> +  // trim leading zeros.
```
// trim trailing zeros
```

2024-07-11 22:17 UTC, corbanbrook commented on packages/core/src/commons/transaction.ts
> +          new Uint8Array([])
yes, bytes now must be Uint8Array

2024-07-11 22:21 UTC, corbanbrook commented on packages/wallet/tests/wallet.spec.ts
> +          expect(nonce === 0n).to.be.true
yes this would be more correct

2024-07-12 16:54 UTC, attente commented on scripts/update-version.js
> +const rootPath = path.resolve(__dirname, '../packages/core')
Thinking about it, I think this makes sense from a cyclic dependency perspective.

2024-07-18 20:44 UTC, corbanbrook commented on packages/0xsequence/tests/browser/wallet-provider/dapp.test.ts
> +      // )
Because Wallet.getBalance no longer exists

2024-07-18 20:44 UTC, corbanbrook commented on packages/0xsequence/tests/browser/wallet-provider/dapp.test.ts
> +      const walletBalanceBefore = await provider2.getBalance(await testAccount.getAddress())
Because Wallet.getBalance no longer exists

2024-07-18 20:52 UTC, corbanbrook commented on packages/0xsequence/tests/browser/window-transport/dapp.test.ts
> +    // assert.equal(chainId2, 31337, 'chainId check')
getChainId no longer exists on the signer

2024-07-18 21:05 UTC, corbanbrook commented on packages/auth/tests/session.spec.ts
> +class CountingSigner extends ethers.AbstractSigner {
ethers.Signer is an interface, AbstractSigner is the class now

2024-07-18 21:33 UTC, corbanbrook commented on packages/core/src/v1/config.ts
> +    return config.signers.map(s => ({ address: s.address, weight: Number(BigInt(s.weight)) }))
The reasoning is that if s.weight is BigNumberish then we need to convert to BigInt first

2024-08-09 19:43 UTC, corbanbrook commented on packages/network/src/json-rpc-provider.ts
> +    // we probably need these in the options of the construtor, etc..
https://github.com/ethers-io/ethers.js/issues/3895

2024-08-26 15:54 UTC, attente approved these changes

2024-08-26 15:55 UTC, merged