add indexergw package
0xsequence/sequence.js pull request #619
Opened 2024-12-04 17:03 UTC by xiam

2024-12-04 17:41 UTC, xiam commented
This example:

```ts
import {
  SequenceIndexerGateway
} from '0xsequence/indexergw'

const ACCOUNT_ADDRESS = '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48'

const indexerGateway = new SequenceIndexerGateway(
  'https://dev-indexer.sequence-dev.app',
)

indexerGateway.getNativeTokenBalance({
  accountAddress: ACCOUNT_ADDRESS,
}).then((res:any) => {
  res.balances.forEach((balance:any) => {
    console.log({balance})
  })
}).catch((error:any) => {
  console.log({error})
})
```

Prints:

```
{
  balance: {
    chainID: 42170,
    balance: {
      accountAddress: '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48',
      balance: '0'
    }
  }
}
{
  balance: {
    chainID: 10,
    balance: {
      accountAddress: '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48',
      balance: '371086549230872066'
    }
  }
}
{
  balance: {
    chainID: 43113,
    balance: {
      accountAddress: '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48',
      balance: '100100000000000000000'
    }
  }
}
{
  balance: {
    chainID: 81457,
    balance: {
      accountAddress: '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48',
      balance: '0'
    }
  }
}
{
  balance: {
    chainID: 660279,
    balance: {
      accountAddress: '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48',
      balance: '0'
    }
  }
}
{
  balance: {
    chainID: 11155420,
    balance: {
      accountAddress: '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48',
      balance: '615667615048000000'
    }
  }
}
{
  balance: {
    chainID: 13473,
    balance: {
      accountAddress: '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48',
      balance: '8100000000000000000'
    }
  }
}
{
  balance: {
    chainID: 97,
    balance: {
      accountAddress: '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48',
      balance: '16003756289696138882'
    }
  }
}
{
  balance: {
    chainID: 11155111,
    balance: {
      accountAddress: '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48',
      balance: '11164700846227378526'
    }
  }
}
{
  balance: {
    chainID: 1101,
    balance: {
      accountAddress: '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48',
      balance: '6827072461408461'
    }
  }
}
...
```

2024-12-04 20:45 UTC, pkieltyka commented
please lets not introduce another "indexergw" package. I know we are doing this on the Go side, but I don't want to do this on the Typescript side.

Please instead keep everything in @0xsequence/indexer and just have packages/indexer/src/indexer.gen.ts and packages/indexer/src/gateway.gen.ts and then for index.ts we can export separately or even we can use the "exports" so developers can `import { IndexerGatewayClient } from '@0xsequence/indexer/gateway'` as an example. But also could also do: `import { IndexerGatewayClient } from '@0xsequence/indexer'` ... we could `export as ....` from index, and bunch of other options.. but lets not introduce "indexergw" package here.

2024-12-04 20:45 UTC, pkieltyka submitted a review, later dismissed
see comment

2024-12-05 15:48 UTC, xiam commented
@corbanbrook This is how output from the latest version looks:

```
[
  {
    chainId: 10,
    result: {
      accountAddress: '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48',
      balance: '371086549230872066'
    }
  },
  {
    chainId: 81457,
    result: {
      accountAddress: '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48',
      balance: '0'
    }
  },
  {
    chainId: 137,
    result: {
      accountAddress: '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48',
      balance: '52408389691068799440368'
    }
  },
  ...
```

2024-12-05 16:16 UTC, corbanbrook requested changes

2024-12-05 16:16 UTC, corbanbrook commented on packages/indexer/src/indexergw.gen.ts
> +  chainID: number
should be `chainId`

2024-12-05 16:16 UTC, corbanbrook commented on packages/indexer/src/indexergw.gen.ts
> +  chainID: number
should be `chainId`

2024-12-05 16:16 UTC, corbanbrook commented on packages/indexer/src/indexergw.gen.ts
> +  chainID: number
should be `chainId`

2024-12-05 16:16 UTC, corbanbrook commented on packages/indexer/src/indexergw.gen.ts
> +  chainID: number
should be `chainId` ??

2024-12-05 16:16 UTC, corbanbrook commented on packages/indexer/src/indexergw.gen.ts
> +  chainID: number
should be `chainId` ??

2024-12-05 16:53 UTC, xiam commented
@corbanbrook I fixed the spelling for the newly introduced `chainId` properties; I'll tackle the legacy ones in a follow-up PR.

2024-12-05 16:54 UTC, corbanbrook submitted a review, later dismissed

2024-12-11 18:32 UTC, corbanbrook approved these changes

2024-12-11 20:22 UTC, merged